# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 21:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_transactions',
            fields=[
                ('username', models.CharField(max_length=20, null=True)),
                ('transaction_date', models.DateTimeField(default=datetime.datetime(2018, 5, 1, 2, 47, 8, 607107))),
                ('quantity', models.FloatField()),
                ('Fat', models.FloatField(max_length=10, null=True)),
                ('SNF', models.FloatField(max_length=10, null=True)),
                ('cattle', models.CharField(choices=[('BUFFALO', 'Buffalo'), ('COW', 'Cow')], default='BUFFALO', max_length=10)),
                ('payment', models.FloatField(null=True)),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], verbose_name='Rating (stars)')),
                ('comment', models.CharField(blank=True, max_length=10000, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 5, 1, 2, 47, 8, 607107))),
            ],
        ),
        migrations.CreateModel(
            name='Sellers_Records',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must have 10 digits.', regex='^\\+?1?\\d{9,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must have 10 digits.', regex='^\\+?1?\\d{9,10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
