# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20180506_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellers_records',
            name='marital_status',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=20),
        ),
        migrations.AlterField(
            model_name='daily_transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 6, 20, 19, 22, 990147)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 6, 20, 19, 22, 990147)),
        ),
    ]
