# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20180506_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 6, 20, 29, 30, 669278)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 6, 20, 29, 30, 669278)),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], verbose_name='Rating (stars)'),
        ),
    ]
