# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 21:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('bill_id', models.IntegerField()),
                ('submit_date', models.DateTimeField(default=datetime.datetime(2018, 5, 1, 2, 46, 54, 700057))),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Sellers_Records')),
            ],
        ),
        migrations.CreateModel(
            name='Milk_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kg_Fat_Rate', models.FloatField(max_length=10)),
                ('Kg_SNF_Rate', models.FloatField(max_length=10)),
                ('up_date', models.DateTimeField(default=datetime.datetime(2018, 5, 1, 2, 46, 54, 700057))),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Record',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=100)),
                ('dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=100)),
                ('join_date', models.DateField(default=datetime.date.today)),
                ('salary', models.IntegerField()),
                ('work', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must have 10 digits.', regex='^\\+?1?\\d{9,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
